#%RAML 1.0
title: Housing Matching Service
version: 3.0.0
baseUri: https://www.hmislynk.com/house-matching-api/v3
mediaType: application/json
securedBy: [oauth_2_0]
securitySchemes:
  oauth_2_0: !include security-schemes/oauth_2_0.raml

/matches:
  displayName: /matches
  get:
    description: Get the list of the proposed matches.
    responses:
      200:
        body:
          example : |
                    {
                       "links":[
                          {
                             "rel":"first",
                             "href":"https://www.hmislynk.com/house-matching-api/matches?page=0&size=1"
                          },
                          {
                             "rel":"self",
                             "href":"https://www.hmislynk.com/house-matching-api/matches?size=1"
                          },
                          {
                             "rel":"next",
                             "href":"https://www.hmislynk.com/house-matching-api/matches?page=1&size=1"
                          },
                          {
                             "rel":"last",
                             "href":"https://www.hmislynk.com/house-matching-api/matches?page=1&size=1"
                          }
                       ],
                       "content":[
                          {
                             "reservationId":"f396b640-faf6-4f2f-98db-26a0c84c8e4f",
                             "eligibleClients":{
                                "clientId":"91dbc8c3-6df6-4702-9733-c84dd67bf1ed",
                                "surveyScore":10,
                                "matched":false,
                                "surveyDate":"09-29-2016 11:05",
                                "dedupClientId":"5dfe2ac2-43af-4d6d-9ee8-0e8fac5e3eg8"
                             },
                             "housingUnitId": "b6e0ecb6-a665-4e95-847f-ec37529a53fb",
                             "matchDate":"2016-10-07",
                             "manualMatch":false,
                             "inactive":false,
                             "dateCreated":"10-25-2016 15:24",
                             "dateUpdated":"10-25-2016 15:24",
                             "userId":"74fe590d-9389-4936-abef-1c18fbf14750",
                             "links":[
                                {
                                   "rel":"history",
                                   "href":"/matches/client/91dbc8c3-6df6-4702-9733-c84dd67bf1ed/status"
                                }
                             ]
                          }
                       ],
                       "page":{
                          "size":1,
                          "totalElements":2,
                          "totalPages":2
                       }
                    }
      403 :
        body:
          example : |
            {
              "error": "Token Not Valid"
            }

  /client/{dedupClientId}:
    description: Perform operations based on the client id.
    uriParameters:
      dedupClientId:
        description: id of the client.
        type: string
    get:
      description: Get the proposed matche for a client_id.
      responses:
        200:
          body:
            example : |
              {
                    "reservation_id":"12345",
                    "client_id": "456788",
                    "housing_unit_id": "09876",
                    "match_date": "2016-10-10",
                    "dateCreated":"10-25-2016 15:24",
                    "dateUpdated":"10-25-2016 15:24",
                    "userId":"74fe590d-9389-4936-abef-1c18fbf14750",
                    "matchedStatus": "true"
              }
        403 :
          body:
            example : |
              {
                "error": "Token Not Valid"
              }
    delete:
      description: |
        Clears off the proposed match for a particular client.
      responses:
        200:
          body:
            example : |
              {
               "deleted":"ok"
              }
        403 :
          body:
            example : |
              {
                "error": "Token Not Valid"
              }
    put:
      description: |
        Used for updating/accepting the match for a client id.
      body:
        application/json:
            example : |
              {	"reservationAdults":"0",
              	"reservationChildren":"2"
              }
      responses:
        200:
          body:
            example : |
              {
               "matched":"ok"
              }
        403 :
          body:
            example : |
              {
                "error": "Token Not Valid"
              }

/eligibleclients:
  displayName: /eligibleclients
  get:
    description: Returns a list of the top eligible clients.
    queryParameters:
        spdattype:
          type: string
          required: false
        status:
          type: string
          required: false
        sort:
          description: |
                To sort data while retrieving. Provide sorting field (if want to sort on multiple fields provide fields with comma separation) and order (asc,desc) with comma separation.
          example: |
                    https://www.hmislynk.com/house-matching-api/rest/eligibleclients?sort=cocScore,surveyDate,asc
    responses:
      200:
        body:
          example : |
            {
               "links":[
                  {
                     "rel":"first",
                     "href":"https://www.hmislynk.com/house-matching-api/eligibleclients?page=0&size=1"
                  },
                  {
                     "rel":"self",
                     "href":"https://www.hmislynk.com/house-matching-api/eligibleclients?size=1"
                  },
                  {
                     "rel":"next",
                     "href":"https://www.hmislynk.com/house-matching-api/eligibleclients?page=1&size=1"
                  },
                  {
                     "rel":"last",
                     "href":"https://www.hmislynk.com/house-matching-api/eligibleclients?page=2&size=1"
                  },
                  {
                     "rel":"scoreprocessingstatus",
                     "href":"https://www.hmislynk.com/house-matching-api/scores/status"
                  },
                  {
                     "rel":"scoreprocessinghistory",
                     "href":"https://www.hmislynk.com/house-matching-api/scores/history"
                  }
               ],
               "content":[
                  {
                     "clientId":"91dbc8c3-6df6-4702-9733-c84dd67bf1ed",
                     "surveyScore":10,
                     "matched":false,
                     "surveyDate":"09-29-2016 11:05",
                     "dateCreated":"10-25-2016 15:24",
                     "dateUpdated":"10-25-2016 15:24",
                     "userId":"74fe590d-9389-4936-abef-1c18fbf14750",
                      "client":{
                              "id":"91dbc8c3-6df6-4702-9733-c84dd67bf1ed",
                               "firstName":"Ryan",
                               "middleName":"",
                               "lastName":"Peterson",
                               "dob":339989400000,
                               "dedupClientId":"5dfe2ac2-43af-4d6d-9ee8-0e8fac5e3eg8"
                            }
                      }
               ],
               "page":{
                  "size":1,
                  "totalElements":3,
                  "totalPages":3
               }
            }
            type: |
                    {
                           "$schema":"http://json-schema.org/draft-04/schema#",
                           "additionalProperties":false,
                           "id":"http://example.com/example.json",
                           "properties":{
                              "content":{
                                 "items":{
                                    "additionalProperties":false,
                                    "properties":{
                                       "clientId":{
                                          "type":"string"
                                       },
                                       "dateCreated":{
                                          "type":"string"
                                       },
                                       "dateUpdated":{
                                          "type":"string"
                                       },
                                       "matched":{
                                          "type":"boolean"
                                       },
                                       "surveyDate":{
                                          "type":"string"
                                       },
                                       "surveyScore":{
                                          "type":"integer"
                                       },
                                       "userId":{
                                          "type":"string"
                                       },
                                       "client":{
                                          "type":"object",
                                          "properties":{
                                             "id":{
                                                "type":"string"
                                             },
                                             "firstName":{
                                                "type":"string"
                                             },
                                             "middleName":{
                                                "type":"string"
                                             },
                                             "lastName":{
                                                "type":"string"
                                             },
                                             "dob":{
                                                "type":"number"
                                             }
                                          }
                                     }
                                    },

                                    "type":"object"
                                 },
                                 "type":"array"
                              },
                              "links":{
                                 "items":{
                                    "additionalProperties":false,
                                    "properties":{
                                       "href":{
                                          "type":"string"
                                       },
                                       "rel":{
                                          "type":"string"
                                       }
                                    },
                                    "required":[
                                       "href",
                                       "rel"
                                    ],
                                    "type":"object"
                                 },
                                 "type":"array"
                              },
                              "page":{
                                 "additionalProperties":false,
                                 "properties":{
                                    "size":{
                                       "type":"integer"
                                    },
                                    "totalElements":{
                                       "type":"integer"
                                    },
                                    "totalPages":{
                                       "type":"integer"
                                    }
                                 },
                                 "required":[
                                    "totalPages",
                                    "totalElements",
                                    "size"
                                 ],
                                 "type":"object"
                              }
                           },
                           "required":[
                              "content",
                              "page",
                              "links"
                           ],
                           "type":"object"
                        }
      403 :
        body:
          example : |
            {
              "error": "Token Not Valid"
            }
  post:
    description: |
              Will add client to the eligible list. Accept json having one or more clients.
              Allowed values for "spdatLabel" field are "FAMILY","YOUTH","SINGLE_ADULT"
    body:
      application/json:
        example: |
                          {
                             "clientDedupId":"74520590-3eb3-11e7-85e4-06c37be0e663",
                             "surveyType":"Servey Type",
                             "surveyScore":"17",
                             "programType":"Program Type",
                             "matched":true,
                             "spdatLabel":"SINGLE_ADULT",
                             "zipcode":"53320",
                             "surveyDate":"05-05-2016 09:12",
                             "ignoreMatchProcess":true,
                             "remarks":"Client not interested"
                          }

    responses:
        200:
          body:
            example : |
              {
                "added":true
              }
        403 :
          body:
            example : |
              {
                "error": "Token Not Valid"
              }

  /{dedupClientId}:
    description: Perform operations based on client_id.
    uriParameters:
      dedupClientId:
        description: id of the client.
        type: string
    get:
      description: Fetch a particular client
      responses:
        200:
          body:
            example : |
                        {
                          "clientId":"800fa63b-8278-414c-83f1-5e29740205a0",
                          "surveyScore":10,
                          "matched":false,
                          "surveyDate":"09-03-2016 04:19",
                          "dateCreated":"10-25-2016 15:24",
                          "dateUpdated":"10-25-2016 15:24",
                          "userId":"74fe590d-9389-4936-abef-1c18fbf14750",
                          "remarks":"Clients eligible for housing unit",
                          "ignoreMatchProcess":false,
                          "client":{
                            "id":"800fa63b-8278-414c-83f1-5e29740205a0",
                            "firstName":"Ryan",
                            "middleName":"",
                            "lastName":"Peterson",
                            "dob":339989400000,
                            "dedupClientId":"5dfe2ac2-43af-4d6d-9ee8-0e8fac5e3eg8"
                          },
                          "links":[
                              {
                                 "rel":"client",
                                 "href":"/hmis-clientapi/rest/v2014/clients/800fa63b-8278-414c-83f1-5e29740205a0"
                              }
                          ]
                        }
            type: |
                              {
                                 "$schema":"http://json-schema.org/draft-04/schema#",
                                 "additionalProperties":false,
                                 "id":"http://example.com/example.json",
                                 "properties":{
                                    "clientId":{
                                       "type":"string"
                                    },
                                    "dateCreated":{
                                       "type":"string"
                                    },
                                    "dateUpdated":{
                                       "type":"string"
                                    },
                                    "ignoreMatchProcess":{
                                       "type":"boolean"
                                    },
                                    "client":{
                                      "type":"object",
                                      "properties":{
                                        "id":{
                                            "type":"string"
                                        },
                                        "firstName":{
                                          "type":"string"
                                        },
                                        "middleName":{
                                          "type":"string"
                                        },
                                        "lastName":{
                                          "type":"string"
                                        },
                                        "dob":{
                                          "type":"number"
                                        }
                                      }
                                    },
                                    "links":{
                                       "items":{
                                          "additionalProperties":false,
                                          "properties":{
                                             "href":{
                                                "type":"string"
                                             },
                                             "rel":{
                                                "type":"string"
                                             }
                                          },
                                          "required":[
                                             "href",
                                             "rel"
                                          ],
                                          "type":"object"
                                       },
                                       "type":"array"
                                    },
                                    "matched":{
                                       "type":"boolean"
                                    },
                                    "remarks":{
                                       "type":"string"
                                    },
                                    "surveyDate":{
                                       "type":"string"
                                    },
                                    "surveyScore":{
                                       "type":"integer"
                                    },
                                    "userId":{
                                       "type":"string"
                                    }
                                 },
                                 "type":"object"
                              }
        403 :
          body:
            example : |
              {
                "error": "Token Not Valid"
              }
        404 :
          body:
            example : |
              {
                "error": "Resource Not Found"
              }
    delete:
      description: Delete a particular client
      responses:
        200:
          body:
            example : |
              {
                "deleted":true
              }
        403 :
          body:
            example : |
              {
                "error": "Token Not Valid"
              }
        404 :
          body:
            example : |
              {
                "error": "Resource Not Found"
              }
    put:
      description: |
              An eligible client, who is already matched and assigned an housing unit can reject the referral (an assigned housig unit can be rejected for various reasons). When this happens, "ignoreMatchProcess" flag will be set to "true" and the hosuing unit will become vacant (available for matching process again) An eligible client, who rejected the refferal, can be made available for matching process by setting "ignoreMatchProcess" to FALSE.
      body:
        application/json:
          example: |
                    {
                      "surveyType": "Servey Type",
                      "surveyScore": "10",
                      "programType": "Program Type",
                      "matched": false,
                      "spdatLabel": "SINGLE_ADULT",
                      "zipcode": "53320",
                      "surveyDate": "05-05-2016 12:12",
                      "remarks":"Client data updated"
                    }
          type: |
                  {
                     "$schema":"http://json-schema.org/draft-04/schema#",
                     "additionalProperties":false,
                     "id":"http://example.com/example.json",
                     "properties":{
                        "matched":{
                           "type":"boolean"
                        },
                        "programType":{
                           "type":"string"
                        },
                        "spdatLabel":{
                           "type":"string"
                        },
                        "surveyDate":{
                           "type":"string"
                        },
                        "surveyScore":{
                           "type":"string"
                        },
                        "surveyType":{
                           "type":"string"
                        },
                        "zipcode":{
                           "type":"string"
                        },
                        "remarks":{
                          "type":"string"
                        }
                     },
                     "required":[
                        "spdatLabel",
                        "surveyScore",
                        "matched"
                     ],
                     "type":"object"
                  }
      responses:
        200:
          body:
            example : |
              {
                "updated":true
              }
        403 :
          body:
            example : |
              {
                "error": "Token Not Valid"
              }
/matches/client/{dedupClientId}/status:
  get:
    description:  TO read a client status history
    responses:
      200:
        body:
          application/json:
            example: |
                      [
                         {
                            "id":"ec501234-c61a-48bd-a85e-580af887a6a4",
                            "clientId":"6f38e63f-7856-4fb1-838f-c03805eab244",
                            "dedupClientId":"5dfe2ac2-43af-4d6d-9ee8-0e8fac5e3eg8",
                            "status":3,
                            "statusDescription":"Agency scheduled appointment with Client",
                            "recipients":{

                            },
                            "active":false,
                            "dateCreated":"10-25-2016 15:24",
                            "dateUpdated":"10-25-2016 15:24",
                            "userId":"74fe590d-9389-4936-abef-1c18fbf14750"                         },
                         {
                            "id":"d406dbb7-cda3-4879-9e5d-989d5bc67b16",
                            "clientId":"6f38e63f-7856-4fb1-838f-c03805eab244",
                             "dedupClientId":"5dfe2ac2-43af-4d6d-9ee8-0e8fac5e3eg8",
                            "status":2,
                            "statusDescription":"Client is contacted by Agency",
                            "recipients":{

                            },
                            "active":false,
                            "dateCreated":"10-13-2016 02:26:09.066",
                            "dateUpdated":"10-13-2016 02:26:09.066",
                            "userId":"74fe590d-9389-4936-abef-1c18fbf14750"
                         },
                         {
                            "id":"d4c767bc-cb85-44f9-a985-0447292fedf6",
                            "clientId":"6f38e63f-7856-4fb1-838f-c03805eab244",
                             "dedupClientId":"5dfe2ac2-43af-4d6d-9ee8-0e8fac5e3eg8",
                            "status":1,
                            "statusDescription":"Email sent to Referral Agency",
                            "recipients":{

                            },
                            "active":false,
                            "dateCreated":"10-13-2016 02:23:59.124",
                            "dateUpdated":"10-13-2016 02:23:59.124",
                            "userId":"74fe590d-9389-4936-abef-1c18fbf14750"
                         }
                      ]
      404:
        body:
          application/json:
            example: |
                  {
                     "error":[
                        {
                           "code":"ERR_CODE_CLIENT_NOT_FOUND",
                           "message":"Client not found"
                        }
                     ]
                  }
  put:
    description: |
          Updates the status of a client matching. A notification will be triggered to the list of recipients set in the request body (recicipents can be part of TO,CC, BCC). Also the notification will be CC'ed to logged-in user (who is authorized to take actions for status to progress to the next levels). User can provide additional comments as well while updating the status of a specific match. Currently, the following are the statuses that are allowed

            Status 1 - Email sent to Referral Agency
            Status 2 - Client is contacted by Agency
            Status 3 - Agency scheduled appointment with Client
            Status 4 - Client missed 1st appointment
            Status 5 - Client missed 2nd appointment
            Status 6 - Paperwork initiated by Agency
            Status 7 - Client accepted referral
            Status 8 - Move-in Preparation initiated by Agency
            Status 9 - Client moved in
            Status 10 - Referral is rejected

    body:
      application/json:
        example: |
            {
               "status":"1",
               "comments":"forwarding to next level",
               "recipients":{
                 "toRecipients":["agent@gmail.com", "client@hmis.com"],
                 "bccRecipients":["agent@gmail.com", "client@hmis.com"],
                 "ccRecipients":["agent@gmail.com", "client@hmis.com"]
               }
            }
        type: |
                {
                  "$schema": "http://json-schema.org/draft-04/schema#",
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string"
                    },
                    "comments": {
                      "type": "string"
                    },
                    "recipients": {
                      "type" : "object",
                      "properties": {
                        "toRecipients" : {"type" : "array"},
                        "bccRecipients" : {"type" : "array"},
                        "ccRecipients" : {"type" : "array"}
                      }
                    }
                  },
                  "required": [
                    "status",
                    "comments",
                    "recipients"
                  ]
                }
    responses:
      200:
      404:
        body:
          application/json:
            example: |
                  {
                     "error":[
                        {
                           "code":"ERR_CODE_CLIENT_NOT_FOUND",
                           "message":"Client not found"
                        }
                     ]
                  }
      400:
        body:
          application/json:
            example: |
                  {
                     "error":[
                        {
                           "code":"ERR_CODE_INVALID_STATUS",
                           "message":"Invalid status. Current status 1"
                        }
                     ]
                  }
